
remote_theme: mmistakes/minimal-mistakes@4.18.1

# Site Settings
name: "Qingqing Yang (楊 青青)"
search: true

# head_scripts:
#   - /custom/js/my

masthead_title: "Qingqing Yang (楊 青青)"

# Publish Settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false


plugins:
  - jekyll-include-cache
