
# remote_theme: mmistakes/minimal-mistakes@4.18.1

# Site Settings
name: "Qingqing Yang (楊 青青)"
author: "Qingqing Yang (楊 青青)"
baseurl : ""
# search: true

# masthead_title: "Qingqing Yang (楊 青青)"

# Publish Settings
include: ["_pages"]
exclude: ["Gemfile", "LICENSE", "Gemfile.lock"]
keep_files: [".git"]

markdown_ext: "md"

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # enable_coderay: false

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page

# plugins:
#   - jekyll-include-cache
